apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: healthcheckpolicies.policy.k8s-go.openshift.org
spec:
  group: policy.k8s-go.openshift.org
  names:
    kind: HealthCheckPolicy
    plural: healthcheckpolicies
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
      type: object
  version: v1alpha1
